spring.application.name=userapi
spring.datasource.url=jdbc:postgresql://localhost:5434/school
spring.datasource.username=postgres
spring.datasource.password=123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


# Show logs level
logging.level.root=INFO
logging.level.com.example.userapi=DEBUG

# Log format
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} - %msg%n
logging.file.name=logs/app.log
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} [%level] %logger - %msg%n