version: '3.8'

services:
  db:
    image: postgres:15
    container_name: postgres-school-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: school
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - db
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  db: